### ISSUE TITLE
k8s jmeter cluster error

### ISSUE THREAD

**Issue by ettwz** [fleeto/jmeter-server#1]
您好，
我参照您 http://blog.fleeto.us/content/zai-kubernetes-shang-shi-yong-jmeter-yun-xing-ya-li-ce-shi 这个博文，尝试搭建k8s的jmeter集群的时候遇到了些问题：
带着net.ipv4.tcp_syncookies=1这个属性pod就会卡在container "jmeter" in pod "jnode-0" is waiting to start: ContainerCreating这里，不带这个的话后面就会连不上1099端口不停重启。跟您请教一下，谢谢！

**Comment by fleeto** [comment]
原则上讲，这个注解是可以去掉的，端口不够的问题可以用多开实例的方式凑合解决，连不上1099的话，你看看是不是因为statefuleset 中的 Pod 的 IP 没能解析？

**Comment by ettwz** [comment]
IP是解析了的 我起了个基础pod 从pod里面ping是可以的 但是telnet连不上
![image](https://user-images.githubusercontent.com/20449556/37690593-e26176b6-2ce6-11e8-91cd-bd9a66246ca0.png)
我的yaml是这样的：
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jnode
  labels:
    app: jmeter
    component: node
spec:
  serviceName: jfarm
  replicas: 2
  selector:
    matchLabels:
      app: jmeter
      component: node
  template:
    metadata:
      labels:
        app: jmeter
        component: node
      annotations:
        security.alpha.kubernetes.io/sysctls: net.ipv4.ip_local_port_range=1024 65000
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jmeter
                - key: component
                  operator: In
                  values:
                  - node
      restartPolicy: Always
      containers:
      - name: jmeter
        image: dustise/jmeter-server
        command:
          - "/jmeter/bin/jmeter"
          - "-n"
          - "-t"
          - "/data/data/jmeter/input/test.jmx"
          - "-R"
          - "jnode-0.jfarm.presstest:1099,jnode-1.jfarm.presstest:1099"
          - "-l"
          - "/data/data/jmeter/output/log"
          - "-j"
          - "/data/data/jmeter/output/joker"
        ports:
        - name: server
          containerPort: 1099
        - name: rmi
          containerPort: 20000
        volumeMounts:
        - name: data
          mountPath: /data/data
        env:
        - name: RMI_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: loadtest
---
apiVersion: v1
kind: Service
metadata:
  name: jfarm
  labels:
    app: jmeter
spec:
  clusterIP: None
  ports:
  - port: 1099
    name: server
  selector:
    app: jmeter
    component: node
```
